name: build

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v4

      - name: setup-apt-llvm
        uses: ./

      - name: test-apt-llvm
        run: |
          sudo apt install -y \
            clang-19 \
            clang-18 \
            clang-17 \
            clang-16
